# General
import = ["~/.config/alacritty/themes/oxocarbon.toml"]
live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
decorations = "Buttonless"
startup_mode = "Maximized"
#padding = { x = 5, y = 10 }
dynamic_padding = false
#opacity = 0.85
#blur = true

[font]
size = 14

[font.normal]
family = "BlexMono Nerd Font Mono"
style = "Light"

[font.italic]
style = "Italic"

[font.bold]
style = "Medium"
